; Example

; [Date]
; date.timezone = "Asia/Tokyo"

; [mbstring]
; mbstring.language = Japanese

;Как это сделать в докере
;error_log = /path/to/php_error.log


error_log = php_errors.log
display_errors = On
